name: ai_teacher_tools
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  flutter_slidable: ^3.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  mockito: ^5.4.4 
  mocktail: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/
