// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKR6kVGUJq_7hjHt6aFkJvA6SiZA5iDX8',
    appId: '1:1098977678454:web:d926b145eb4b57cb97fb57',
    messagingSenderId: '1098977678454',
    projectId: 'ai-teacher-tools',
    authDomain: 'ai-teacher-tools.firebaseapp.com',
    storageBucket: 'ai-teacher-tools.firebasestorage.app',
    measurementId: 'G-V7BDG9V81X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0yWDueg4yDfVLzKVUsvxGVNpAACJkjM',
    appId: '1:1098977678454:android:97fd237b5c65386597fb57',
    messagingSenderId: '1098977678454',
    projectId: 'ai-teacher-tools',
    storageBucket: 'ai-teacher-tools.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tXwsFX7NRKIoMbgiWNMZ2hQYeLGSNx0',
    appId: '1:1098977678454:ios:f58e5fd63b3828f697fb57',
    messagingSenderId: '1098977678454',
    projectId: 'ai-teacher-tools',
    storageBucket: 'ai-teacher-tools.firebasestorage.app',
    iosBundleId: 'com.example.aiTeacherTools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tXwsFX7NRKIoMbgiWNMZ2hQYeLGSNx0',
    appId: '1:1098977678454:ios:f58e5fd63b3828f697fb57',
    messagingSenderId: '1098977678454',
    projectId: 'ai-teacher-tools',
    storageBucket: 'ai-teacher-tools.firebasestorage.app',
    iosBundleId: 'com.example.aiTeacherTools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKR6kVGUJq_7hjHt6aFkJvA6SiZA5iDX8',
    appId: '1:1098977678454:web:9d80293ffa893f7197fb57',
    messagingSenderId: '1098977678454',
    projectId: 'ai-teacher-tools',
    authDomain: 'ai-teacher-tools.firebaseapp.com',
    storageBucket: 'ai-teacher-tools.firebasestorage.app',
    measurementId: 'G-QB1J02D0T1',
  );
}
